name: ademicon_app
description: Aplicativo ADEMICON Londrina

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  csv: ^6.0.0
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  email_validator: ^2.1.17
  share_plus: ^7.2.2
  file_selector: ^0.9.5
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  mask_text_input_formatter: ^2.9.0
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.5
  flutter_local_notifications: ^19.4.2
  flutter_local_notifications_linux: ^6.0.0
  flutter_local_notifications_windows: ^1.0.3
  timezone: ^0.10.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Linha_Lateral.png
    - assets/Logo.png
    - .env
